version: "3"
services:
  Jenkin-Docker:
  # replace username/repo:tag with your name and image details
    image: jenkinsci/blueocean
    restart: on-failure
    ports:
      - "8080:8080"
       
    networks:
      - webnet
networks:
  webnet:
